POST http://localhost/backendSoApp/public/api/login
Content-Type: application/json

{
    "username": "testinguser",
    "password": "password123"
}

### REQUEST  ###
GET http://localhost/backendSoApp/public/api/stockopname/cekmasterso
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2JhY2tlbmRTb0FwcC9wdWJsaWMvYXBpL2xvZ2luIiwiaWF0IjoxNzA1NDYyNDc2LCJleHAiOjE3MDU0OTg0NzYsIm5iZiI6MTcwNTQ2MjQ3NiwianRpIjoiSWhIUjhTSjM3OGh3dWNwWCIsInN1YiI6IjEiLCJwcnYiOiI5ZjM4ZWVhZTc2OGM4MDE1ZDkzODliNDhlNGM0MzZmMGJhNWJjMTE0IiwiaWRfdXNlciI6MX0.36RA4jXCkoiRZv-1BWnIRv_Cv2rst-rSXfPFR8bvfF4

### REQUEST  ###
GET http://ec2-13-51-158-189.eu-north-1.compute.amazonaws.com/backendSoApp/public/api/stockopname/cekmasterso
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTkyLjE2OC4xOTQuMTY1L2JhY2tlbmRTb0FwcC9wdWJsaWMvYXBpL2xvZ2luIiwiaWF0IjoxNzA1MTI0MDE4LCJleHAiOjE3MDUxNjAwMTgsIm5iZiI6MTcwNTEyNDAxOCwianRpIjoiVmZLZ1laS280WjRjUXE4ZCIsInN1YiI6IjEiLCJwcnYiOiI5ZjM4ZWVhZTc2OGM4MDE1ZDkzODliNDhlNGM0MzZmMGJhNWJjMTE0IiwiaWRfdXNlciI6MX0.efX0_EBsYmhNmPPQRYsTeSsQrLtKw708_ff5d5QPfuQ
